In [1]:
import numpy as np

In [2]:
mylist = [1., 2., 3., 4.]
mynparray = np.array(mylist)
mynparray

array([ 1.,  2.,  3.,  4.])

In [4]:
one_vector = np.ones(4)
print one_vector

[ 1.  1.  1.  1.]


In [6]:
one2Darray = np.ones((2,4))
print one2Darray

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [7]:
zero_vector = np.zeros(4)
print zero_vector

[ 0.  0.  0.  0.]


In [8]:
empty_vector = np.empty(5)
print empty_vector

[  3.26703003e-316   2.59179328e-316   2.00164096e-316   1.48430798e-316
   2.91305927e-316]


In [9]:
mynparray[2]

3.0

In [10]:
my_matrix = np.array([[1,2,3], [4, 5, 6]])
print my_matrix

[[1 2 3]
 [4 5 6]]


In [14]:
print my_matrix[1, 2]

6


In [15]:
print my_matrix[0:2, 2]

[3 6]


In [16]:
print my_matrix[0, 0:3]

[1 2 3]


In [17]:
fib_indices = np.array([1, 1, 2, 3])
random_vector = np.random.random(10)
print random_vector

[ 0.47917954  0.80927083  0.36425991  0.89245554  0.64264995  0.3708749
  0.805137    0.42543033  0.43100124  0.90912266]


In [18]:
print random_vector[fib_indices]

[ 0.80927083  0.80927083  0.36425991  0.89245554]


In [19]:
my_vector = np.array([1, 2, 3, 4])
select_index = np.array([True, False, True, False])
print my_vector[select_index]

[1 3]


In [20]:
select_cols = np.array([True, False, True])
select_rows = np.array([False, True])

In [21]:
print my_matrix[select_rows, :]

[[4 5 6]]


In [22]:
print my_matrix[:, select_cols]

[[1 3]
 [4 6]]


In [23]:
my_array = np.array([1., 2., 3., 4.])
print my_array*my_array

[  1.   4.   9.  16.]


In [24]:
print my_array**2

[  1.   4.   9.  16.]


In [25]:
print my_array -np.ones(4)

[ 0.  1.  2.  3.]


In [26]:
print my_array + np.ones(4)

[ 2.  3.  4.  5.]


In [27]:
print my_array/3

[ 0.33333333  0.66666667  1.          1.33333333]


In [28]:
print my_array/np.array([2., 3., 4.,5.])

[ 0.5         0.66666667  0.75        0.8       ]


In [29]:
print np.sum(my_array)

10.0


In [30]:
print np.average(my_array)

2.5


In [32]:
print np.sum(my_array)/len(my_array)

2.5


In [34]:
array1 = np.array([1., 2.,3.,4.])
array2 = np.array([2.,3.,4.,5.])
print np.dot(array1, array2)

40.0


In [35]:
print np.sum(array1*array2)

40.0


In [36]:
array1_mag = np.sqrt(np.dot(array1, array1))
print array1_mag

5.47722557505


In [37]:
print np.sqrt(np.sum(array1*array1))

5.47722557505


In [43]:
my_features = np.array([[1., 2.], [3.,4.], [5., 6.], [7., 8.]])
print my_features
print my_features.shape

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]
(4L, 2L)


In [44]:
my_weights = np.array([0.4, 0.5])
print my_weights
print my_weights.shape

[ 0.4  0.5]
(2L,)


In [40]:
my_predictions = np.dot(my_features, my_weights)
print my_predictions

[ 1.4  3.2  5.   6.8]


In [47]:
my_matrix = my_features
my_array = np.array([0.3, 0.4, 0.5, 0.6])
my_array.shape

(4L,)

In [46]:
print np.dot(my_array, my_matrix)

[  8.2  10. ]


In [48]:
matrix_1 = np.array([[1., 2., 3.], [4., 5., 6.]])
print matrix_1
print matrix_1.shape
matrix_2 = np.array([[1., 2.], [3., 4.], [5., 6.]])
print matrix_2
print matrix_2.shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
(2L, 3L)
[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
(3L, 2L)


In [49]:
print np.dot(matrix_1, matrix_2)

[[ 22.  28.]
 [ 49.  64.]]
